services:
  productmanagement.api:
    image: ${DOCKER_REGISTRY-}productmanagementapi
    build:
      context: .
      dockerfile: ProductManagement.API/Dockerfile
    ports:
      - "9002:8080"
      - "9091:8081"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:8081;http://+:8080
      - ASPNETCORE_HTTPS_PORT=8081
